#!/bin/sh
# Debian vtwm package post-removal script
# Copyright 1999 Branden Robinson.
# Licensed under the GNU General Public License, version 2.  See the file
# /usr/share/common-licenses/GPL or <http://www.gnu.org/copyleft/gpl.txt>.

# $Id$

set -e

trap "echo ;\
      echo 'Received signal.  Aborting removal of vtwm package.' ;\
      echo ;\
      exit 1" 1 2 3 15

#DEBHELPER#

if [ "$1" = "purge" ]; then
    if [ -d /etc/X11/vtwm ]; then
        rm -r /etc/X11/vtwm
    fi
fi

exit 0

# vim:set ai et sts=4 sw=4 tw=80:
